version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: webapp_test
      POSTGRES_USER: webapp_user
      POSTGRES_PASSWORD: webapp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
